.TH SUPTIME 1

.SH NAME
suptime \- Tell how long the system has been running.
.SH SYNOPSIS
.B suptime
[\fB\-s\fR|\fB\-m\fR|\fB\-H\fR|\fB\-d\fR|\fB\-f\fR FORMAT|\fB\-h\fR]
.SH DESCRIPTION
.B suptime
outputs a single unit representation of system uptime.
By default outputs in seconds.
.SH OPTIONS
.TP
.BR \-s
Output in seconds.
.TP
.BR \-m
Output in minutes.
.TP
.BR \-H
Output in hours.
.TP
.BR \-d
Output in days.
.TP
.BR \-h
Display help.
.TP
.BR \-f\ FORMAT
Output in custom format
.PP
Interpreted sequences for FORMAT are:
.TP
%Y
years since boot
.TP
%d
days since boot (by itself equivalent to -d)
.TP
%H
hours since boot (by itself equivalent to -H)
.TP
%m
minutes since boot (by itself equivalent to -m)
.TP
%s
seconds since boot (by itself equivalent to -s)
.TP
%D
day in current year since boot (if the system has been up for 1 year and 2 days, %D will become 2)
.TP
%h
hour in current day since boot (if the system has been up for 1 day and 2 hours, %h will become 2)
.TP
%M
minutes in current hour since boot (if the system has been up for 1 hour and 2 minutes, %M will become 2)
.TP
%S
seconds in current minute since boot (if the system has been up for 1 minute and 2 seconds, %S will become 2)
.TP
%T
equivalent to %H:%M:%S
.TP
%n
a newline character
.TP
%t
a tab character
.SH EXAMPLES
To output system uptime in seconds
.PP
.nf
.RS
suptime
.RE
.fi
.PP
You can also include use the \fB\-s\fR option although it is not necessary to
output seconds.
.PP
To output system uptime in days
.PP
.nf
.RS
suptime -d
.RE
.fi
.PP
To output system uptime in hour:minute:second format
.PP
.nf
.RS
suptime -f %T
.RE
.fi
.PP
Naively emulate GNU uptime(1) -p/--pretty output
.PP
.nf
.RS
suptime -f "up %d days, %H hours, %M minutes"
.RE
.fi
