.TH LINES 1
.SH NAME
line \- extract lines from input
.SH SYNOPSIS
.B lines
.IR [LINES...]
.SH DESCRIPTION
.B lines
extracts one or more lines from stdin. If multiple lines are provided, they will
be sorted numerically. If the same line is specified twice, it will only be
extracted once.
.SH EXAMPLES
Get the 3rd line from the file lines.1
.PP
.nf
.RS
lines 3 < lines.1
.RE
.fi
.PP
Get the 3rd, 4th and 5th lines from the file lines.1
.PP
.nf
.RS
lines 3 5 4 < lines.1
.RE
.fi
