.TH COUNTDOWN 1
.SH NAME
countdown \- start a countdown timer
.SH SYNOPSIS
.B countdown
.IR time
.SH DESCRIPTION
.B countdown
counts down from \fItime\fR to 0 seconds.
.SH OPTIONS
.TP
.I time
The time in seconds to countdown from.
.SH EXAMPLES
Start a 5 second countdown
.PP
.nf
.RS
countdown 5
.RE
.fi
