#!/usr/bin/env sh
#
# pasta: simple ssh-based paste bin (client)
# author: Hiltjo Posthuma <hiltjo@codemass.org>, Dylan Lom <djl@dylanlom.com>
# see-also: https://codemadness.org/paste-service.html

sshdomain="djl@p.dlom.cc"
destpath="/usr/local/www/p.dlom.cc"
destdomain="http://p.dlom.cc"

argv0="$0"

usage() {
	echo "usage: $argv0 [-p | -c] filename"
	exit 1
}

while [ "$#" -gt 1 ]; do
    case "$1" in
        '-p') png='true'; ;;
        '-c') concat='true'; ;;
        *) usage ;;
    esac
    shift
done

name="$1"
[ -z "$name" ] && usage

if [ -z "$concat" ]; then
    ([ ! -z "$png" ] && import png:- || cat) | \
        ssh "$sshdomain" "cat > $destpath/$name"
else
    ssh "$sshdomain" "cat >> $destpath/$name"
fi

echo "$destdomain/$name"

